---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/meseconslab.minetest.ch
  tasks:
    - name: Checkout git
      shell: |
        git reset --hard
        git submodule --sync
        git pull --recurse-submodules
      args:
        chdir: "{{ compose_directory }}"

    - name: Template files
      with_list:
       - "minetest.conf"
       - "matterbridge.toml"
       - "docker-compose.yml"
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"

    - name: Create and start services
      shell: docker-compose up -d --remove-orphans
      args:
        chdir: "{{ compose_directory }}"
